spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${IDENTITY_ORACLE_URL:jdbc:oracle:thin:@//172.16.88.115:1521/XEPDB1}
    username: ${IDENTITY_ORACLE_USERNAME:IDENTITY_APP}
    password: ${IDENTITY_ORACLE_PASSWORD:ora123}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${IDENTITY_REDIS_HOST:172.16.88.115}
      port: ${IDENTITY_REDIS_PORT:6379}
      password: ${IDENTITY_REDIS_PASSWORD:StrongRedisPassword}
      database: ${IDENTITY_REDIS_DATABASE:3}
      timeout: ${IDENTITY_REDIS_TIMEOUT:2s}
      connect-timeout: ${IDENTITY_REDIS_CONNECT_TIMEOUT:2s}
      repositories:
        enabled: false
logging:
  config: classpath:log4j2-spring.xml
identity-reference:
  persistence:
    oracle:
      enabled: true
  cache:
    redis:
      enabled: true
      key-prefix: "${IDENTITY_REDIS_KEY_PREFIX:identity-ref:v1:}"
      entry-ttl: ${IDENTITY_REDIS_ENTRY_TTL:24h}