spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: ${IDENTITY_ORACLE_URL:jdbc:oracle:thin:@//172.16.88.115:1521/XEPDB1}
    username: ${IDENTITY_ORACLE_USERNAME:IDENTITY_APP}
    password: ${IDENTITY_ORACLE_PASSWORD:ora123}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
