package com.isc.identityreference.provider.spi;

public enum ProviderErrorCode {
    INVALID_REQUEST, AUTHENTICATION_FAILED, AUTHORIZATION_FAILED, RATE_LIMITED,
    TIMEOUT, UNAVAILABLE, MALFORMED_RESPONSE, VALIDATION_FAILED, INTERNAL_ERROR
}
