package com.isc.identityreference.admin;
import jakarta.persistence.*;import java.time.Instant;import java.time.LocalDate;
@Entity @Table(name="identity_test_identity")
public class TestIdentityEntity{
 @Id @Column(name="identity_reference_id",length=36,nullable=false) private String identityReferenceId;
 @Column(name="test_identity_label",length=120) private String testIdentityLabel;@Column(name="scenario_tag",length=120)private String scenarioTag;@Column(name="nationality",length=100)private String nationality;@Column(name="expiration_date")private LocalDate expirationDate;
 @Column(name="photo_version",length=64)private String photoVersion;@Lob @Column(name="photo_content")private byte[] photoContent;@Column(name="photo_content_type",length=64)private String photoContentType;@Column(name="photo_size")private Long photoSize;@Column(name="biometric_status",length=32,nullable=false)private String biometricStatus="NOT_AVAILABLE";
 @Column(name="created_by",length=128)private String createdBy;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="updated_by",length=128)private String updatedBy;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 public String getIdentityReferenceId(){return identityReferenceId;}public void setIdentityReferenceId(String v){identityReferenceId=v;}public String getTestIdentityLabel(){return testIdentityLabel;}public void setTestIdentityLabel(String v){testIdentityLabel=v;}public String getScenarioTag(){return scenarioTag;}public void setScenarioTag(String v){scenarioTag=v;}public String getNationality(){return nationality;}public void setNationality(String v){nationality=v;}public LocalDate getExpirationDate(){return expirationDate;}public void setExpirationDate(LocalDate v){expirationDate=v;}public String getPhotoVersion(){return photoVersion;}public void setPhotoVersion(String v){photoVersion=v;}public byte[] getPhotoContent(){return photoContent==null?null:photoContent.clone();}public void setPhotoContent(byte[] v){photoContent=v==null?null:v.clone();}public String getPhotoContentType(){return photoContentType;}public void setPhotoContentType(String v){photoContentType=v;}public Long getPhotoSize(){return photoSize;}public void setPhotoSize(Long v){photoSize=v;}public String getBiometricStatus(){return biometricStatus;}public void setBiometricStatus(String v){biometricStatus=v;}public String getCreatedBy(){return createdBy;}public void setCreatedBy(String v){createdBy=v;}public Instant getCreatedAt(){return createdAt;}public void setCreatedAt(Instant v){createdAt=v;}public String getUpdatedBy(){return updatedBy;}public void setUpdatedBy(String v){updatedBy=v;}public Instant getUpdatedAt(){return updatedAt;}public void setUpdatedAt(Instant v){updatedAt=v;}
}