package com.isc.identityreference.refresh;
import com.isc.identityreference.application.IdentityReferenceStore;
import com.isc.identityreference.application.LookupKeyFingerprint;
import com.isc.identityreference.cache.l1.CaffeineL1Cache;
import com.isc.identityreference.cache.redis.RedisL2Cache;
import com.isc.identityreference.domain.freshness.*;
import com.isc.identityreference.domain.identity.*;
import com.isc.identityreference.domain.lifecycle.IdentityLifecycleState;
import com.isc.identityreference.domain.provider.*;
import com.isc.identityreference.observability.IdentityReferenceMetrics;
import com.isc.identityreference.provider.IdentityProviderRegistry;
import com.isc.identityreference.provider.spi.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.task.AsyncTaskExecutor;
import org.springframework.stereotype.Service;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.*;
@Service public class IdentityReferenceRefreshService{
 private final IdentityReferenceStore store;private final IdentityProviderRegistry providers;private final CaffeineL1Cache l1;private final RedisL2Cache l2;private final RefreshPolicyResolver policies;private final RefreshProperties properties;private final RefreshLeaseManager leases;private final RefreshQuotaGuard quota;private final IdentityReferenceMetrics metrics;private final Executor refreshExecutor;private final AsyncTaskExecutor providerExecutor;
 public IdentityReferenceRefreshService(IdentityReferenceStore store,IdentityProviderRegistry providers,CaffeineL1Cache l1,ObjectProvider<RedisL2Cache> l2Provider,RefreshPolicyResolver policies,RefreshProperties properties,RefreshLeaseManager leases,RefreshQuotaGuard quota,IdentityReferenceMetrics metrics,@Qualifier("identityRefreshExecutor") Executor refreshExecutor,@Qualifier("identityProviderExecutor") AsyncTaskExecutor providerExecutor){this.store=store;this.providers=providers;this.l1=l1;this.l2=l2Provider.getIfAvailable();this.policies=policies;this.properties=properties;this.leases=leases;this.quota=quota;this.metrics=metrics;this.refreshExecutor=refreshExecutor;this.providerExecutor=providerExecutor;}
 public RefreshResult getOrRefresh(IdentityLookupKey key,String providerId,Instant now){String hash=LookupKeyFingerprint.of(key);Optional<IdentityReference> ref=l1.get(hash);if(ref.isEmpty()&&l2!=null)ref=l2.get(hash);if(ref.isEmpty())ref=store.find(key);if(ref.isPresent()){FreshnessState state=ref.get().freshnessAt(now);if(state==FreshnessState.FRESH){cache(hash,ref.get());return new RefreshResult(RefreshResult.Status.SKIPPED,ref.get(),"fresh","-");}if(state==FreshnessState.STALE&&properties.isStaleWhileRefresh()){cache(hash,ref.get());try{refreshExecutor.execute(()->refresh(key,providerId,Instant.now(),true,"automatic"));}catch(RejectedExecutionException ex){metrics.refreshOutcome(providerId,"automatic","queue-rejected");}metrics.refreshOutcome(providerId,"automatic","stale-served");return new RefreshResult(RefreshResult.Status.STALE_SERVED,ref.get(),"stale reference served while refresh runs","-");}}return refresh(key,providerId,now,true,"automatic");}
 public RefreshResult forceRefresh(IdentityLookupKey key,String providerId,Instant now){return refresh(key,providerId,now,true,"admin");}
 public RefreshResult scheduledRefresh(IdentityLookupKey key,String providerId,Instant now){return refresh(key,providerId,now,true,"scheduled");}
 public RefreshResult refresh(IdentityLookupKey key,String providerId,Instant now,boolean requireLease){return refresh(key,providerId,now,requireLease,"automatic");}
 private RefreshResult refresh(IdentityLookupKey key,String providerId,Instant now,boolean requireLease,String trigger){
  String operationId=UUID.randomUUID().toString();long start=System.nanoTime();RefreshPolicy policy=policies.resolve(providerId);RefreshLeaseManager.Lease lease=null;boolean quotaEntered=false;IdentityReference existing=store.find(key).orElse(null);
  try{
   if(requireLease){lease=leases.tryAcquire(LookupKeyFingerprint.of(key),properties.getLeaseDuration()).orElse(null);if(lease==null){metrics.refreshOutcome(providerId,trigger,"locked");return new RefreshResult(RefreshResult.Status.LOCKED,existing,"Refresh already in progress",operationId);}}
   if(!quota.tryEnter(policy)){metrics.refreshOutcome(providerId,trigger,"quota-deferred");return new RefreshResult(RefreshResult.Status.LOCKED,existing,"Provider quota temporarily exhausted",operationId);}quotaEntered=true;
   IdentityProvider provider=providers.find(providerId).orElse(null);if(provider==null){recordFailure(key,providerId,existing,policy,"PROVIDER_FAILURE","Provider is not available",now);metrics.refreshOutcome(providerId,trigger,"provider-unavailable");return new RefreshResult(RefreshResult.Status.FAILED,existing,"Provider is not available",operationId);}
   ProviderLookupResult result=lookupWithRetry(provider,key,policy);
   if(result.status()==ProviderLookupStatus.NOT_FOUND){recordFailure(key,providerId,existing,policy,"NOT_FOUND","No matching identity was found",now);metrics.refreshOutcome(providerId,trigger,"not-found");return new RefreshResult(RefreshResult.Status.NOT_FOUND,existing,"No matching identity was found",operationId);}
   if(result.status()!=ProviderLookupStatus.FOUND){String status=result.error()!=null&&result.error().code()==ProviderErrorCode.TIMEOUT?"PROVIDER_TIMEOUT":"PROVIDER_FAILURE";recordFailure(key,providerId,existing,policy,status,result.error()==null?"Provider refresh failed":result.error().safeMessage(),now);metrics.refreshOutcome(providerId,trigger,status.toLowerCase());return new RefreshResult(RefreshResult.Status.FAILED,existing,"Provider refresh failed",operationId);}
   Instant retrieved=result.retrievedAt();Freshness freshness=new Freshness(retrieved,retrieved.plus(policy.ttl()),retrieved.plus(policy.ttl()).plus(policy.staleGrace()));
   IdentityReference reference=new IdentityReference(existing==null?IdentityReferenceId.newId():existing.id(),key,result.attributes(),List.of(new ProviderRecord(result.providerId(),result.providerRecordId(),result.authority(),ProviderRecordState.CURRENT,result.attributes(),freshness,retrieved)),existing==null?List.of():existing.biometricReferences(),IdentityLifecycleState.ACTIVE,freshness,existing==null?now:existing.createdAt(),now);
   store.save(reference,freshness.freshUntil().minus(policy.refreshBeforeExpiry()),policy.version());cache(LookupKeyFingerprint.of(key),reference);metrics.refreshOutcome(providerId,trigger,"refreshed");metrics.refreshDuration(providerId,trigger,System.nanoTime()-start);return new RefreshResult(RefreshResult.Status.REFRESHED,reference,"Identity reference refreshed",operationId);
  }catch(RuntimeException ex){metrics.refreshOutcome(providerId,trigger,"error");metrics.refreshDuration(providerId,trigger,System.nanoTime()-start);return new RefreshResult(RefreshResult.Status.FAILED,existing,"Refresh failed",operationId);}
  finally{if(quotaEntered)quota.exit(providerId);if(lease!=null)leases.release(lease);}
 }
 private void recordFailure(IdentityLookupKey key,String providerId,IdentityReference existing,RefreshPolicy policy,String status,String safeError,Instant now){if(existing==null)return;int retryCount=Math.min(policy.maxRefreshFailures(),store.currentRefreshRetryCount(key)+1);long exponent=Math.min(30,Math.max(0,retryCount-1));long delay=Math.min(policy.refreshFailureMaxBackoff().toMillis(),policy.refreshFailureInitialBackoff().toMillis()*(1L<<exponent));Instant next=retryCount>=policy.maxRefreshFailures()?now.plus(policy.ttl()):now.plusMillis(delay);store.recordRefreshFailure(key,providerId,retryCount>=policy.maxRefreshFailures()?"RETRY_EXHAUSTED":status,safeError,retryCount,next,now);}
 private ProviderLookupResult lookupWithRetry(IdentityProvider provider,IdentityLookupKey key,RefreshPolicy policy){ProviderLookupResult result=null;for(int attempt=1;attempt<=policy.maxAttempts();attempt++){try{Future<ProviderLookupResult> f=providerExecutor.submit(()->provider.lookup(key));result=f.get(policy.timeout().toMillis(),TimeUnit.MILLISECONDS);}catch(TimeoutException e){result=ProviderLookupResult.error(provider.descriptor().providerId(),"timeout",ProviderAuthority.UNKNOWN,new ProviderError(ProviderErrorCode.TIMEOUT,true,"Provider request timed out"),Instant.now());}catch(InterruptedException e){Thread.currentThread().interrupt();result=ProviderLookupResult.error(provider.descriptor().providerId(),"interrupted",ProviderAuthority.UNKNOWN,new ProviderError(ProviderErrorCode.TIMEOUT,true,"Provider request interrupted"),Instant.now());}catch(ExecutionException|RejectedExecutionException e){result=ProviderLookupResult.error(provider.descriptor().providerId(),"error",ProviderAuthority.UNKNOWN,new ProviderError(ProviderErrorCode.UNAVAILABLE,true,"Provider request failed"),Instant.now());}if(result.status()!=ProviderLookupStatus.ERROR||result.error()==null||!result.error().retryable())return result;if(attempt<policy.maxAttempts())try{Thread.sleep(Math.min(policy.maxBackoff().toMillis(),policy.initialBackoff().toMillis()*(1L<<(attempt-1))));}catch(InterruptedException e){Thread.currentThread().interrupt();return result;}}return result;}
 private void cache(String hash,IdentityReference reference){l1.put(hash,reference);if(l2!=null)l2.put(hash,reference);}
}